name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

env:
  VERSION: "1.0"

jobs:
  build:
    name: Build Alpine ${{ matrix.image.variant }} image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - variant: "3.14"
          - variant: "3.15"
          - variant: "3.16"
          - variant: "3.17"
            latest: "true"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Build image
        run: |
          if [ "${{ matrix.image.latest }}" = "true" ]; then
            latest="--image-name=ghcr.io/${{ github.repository }}/base:latest-alpine"
          else
            latest=""
          fi
          devcontainer build \
            --workspace-folder . \
            --platform linux/amd64,linux/arm64 \
            --image-name=ghcr.io/${{ github.repository }}/base:${{ env.VERSION }}-alpine-${{ matrix.image.variant }} \
            --image-name=ghcr.io/${{ github.repository }}/base:latest-alpine-${{ matrix.image.variant }} \
            ${latest} \
            --push
        env:
          VARIANT: ${{ matrix.image.variant }}
