name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_VERSION: "1.0.3"

jobs:
  publish-image:
    name: Publish Alpine image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Build image
        run: |
          devcontainer build \
            --workspace-folder images/src/alpine-base \
            --platform linux/amd64,linux/arm64 \
            --image-name=ghcr.io/${{ github.repository }}/alpine-base:${{ env.IMAGE_VERSION }} \
            --image-name=ghcr.io/${{ github.repository }}/alpine-base:latest \
            --push

  publish-features:
    name: Publish features
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Publish features
        run: devcontainer features publish features/src --namespace "${{ github.repository }}"

  publish-templates:
    name: Publish templates
    runs-on: ubuntu-latest
    needs:
      - publish-image
      - publish-features
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Publish templates
        run: devcontainer templates publish templates/src --namespace "${{ github.repository }}"
