name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

env:
  VERSION: "1.0.1"

jobs:
  build-image:
    name: Build Alpine image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Build image
        run: |
          if [ "${{ matrix.image.latest }}" = "true" ]; then
            latest="--image-name=ghcr.io/${{ github.repository }}/base:latest-alpine"
          else
            latest=""
          fi
          devcontainer build \
            --workspace-folder . \
            --platform linux/amd64,linux/arm64 \
            --image-name=ghcr.io/${{ github.repository }}/alpine-base:${{ env.VERSION }} \
            --image-name=ghcr.io/${{ github.repository }}/alpine-base:latest \
            --push

  build-features:
    name: Build features
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Publish features
        run: devcontainer features publish features/src --namespace "${{ github.repository }}"
